### ISSUE TITLE
Not enough pink.

### ISSUE THREAD

**Issue by lewpar** [VictorPersson/vuector-website#1]
Hello,

Please excuse me sir, but I think there's a lack of pink on your site. Remember to stay hydrated with coffee mister developer!

Lots of love.

**Comment by VictorPersson** [comment]
Dear mr Parker,

I am so sorry to hear that you have had such a poor experience with the website.

Customer satisfaction is always the number one priority for us. I'm deeply sorry that that wasn't clearly demonstrated to you.

 **As a sign of our good will, our lead software pinkitech have pushed a pink hotfix, only for you. Please visit the live beta at https://victorp.se/asmrdarlinglew

I apologize again for any trouble this may have caused you. Good luck with your business, and I wish you all the best.

Let me know if you have any more questions, comments, or concerns.

_Best,
Victor Per Erik Persson, lead pink designer._
